"""
Test Improver Agent - Generates improved version of test code based on analysis.
"""

import logging
from typing import Dict

logger = logging.getLogger(__name__)


class TestImproverAgent:
    """Agent responsible for improving test code based on analysis."""
    
    def __init__(self):
        """Initialize test improver agent."""
        logger.info("Test Improver Agent initialized")
    
    def generate_improved_test_suite(
        self,
        analysis_result: Dict,
        original_code: str
    ) -> str:
        """
        Generate improved test suite based on analysis.
        
        Args:
            analysis_result: Analysis result from TestAnalyzerAgent
            original_code: Original test code
        
        Returns:
            Improved test code as string
        """
        logger.info("Generating improved test suite...")
        
        # Extract test class name
        test_class_name = analysis_result.get('test_class_name', 'UnknownTestClass')
        
        # Build improved code from suggested_code of each method
        improved_code_parts = []
        
        # Add header comment
        improved_code_parts.append(
            f"/**\n"
            f" * Improved Test Suite: {test_class_name}\n"
            f" * Generated by TAI-EvalGenTCS\n"
            f" * Overall Compliance Score: {analysis_result.get('overall_compliance_score', 'N/A')}\n"
            f" */\n"
        )
        
        # Extract class declaration from original code
        class_declaration = self._extract_class_declaration(original_code)
        if class_declaration:
            improved_code_parts.append(class_declaration)
            improved_code_parts.append("\n")
        
        # Add improved test methods
        test_methods = analysis_result.get('test_methods', [])
        for method in test_methods:
            suggested_code = method.get('suggested_code', '')
            if suggested_code:
                improved_code_parts.append(f"    {suggested_code}\n\n")
        
        # Add closing brace
        improved_code_parts.append("}\n")
        
        improved_code = ''.join(improved_code_parts)
        
        logger.info(f"Generated improved test suite ({len(improved_code)} chars)")
        
        return improved_code
    
    def _extract_class_declaration(self, original_code: str) -> str:
        """
        Extract class declaration and imports from original code.
        
        Args:
            original_code: Original test code
        
        Returns:
            Class declaration with imports
        """
        lines = original_code.split('\n')
        declaration_parts = []
        in_class = False
        
        for line in lines:
            # Add imports and package declarations
            if line.strip().startswith('package ') or \
               line.strip().startswith('import ') or \
               line.strip().startswith('//') or \
               line.strip().startswith('/*') or \
               line.strip() == '':
                declaration_parts.append(line)
            
            # Add class declaration
            elif 'class ' in line and not in_class:
                # Extract just the class declaration line
                if '{' in line:
                    declaration_parts.append(line.split('{')[0] + '{')
                else:
                    declaration_parts.append(line)
                in_class = True
                break
        
        return '\n'.join(declaration_parts)
    
    def generate_improvement_summary(self, analysis_result: Dict) -> str:
        """
        Generate summary of improvements made.
        
        Args:
            analysis_result: Analysis result from TestAnalyzerAgent
        
        Returns:
            Summary as formatted string
        """
        summary_parts = []
        
        summary_parts.append("# Test Suite Improvement Summary\n")
        summary_parts.append(f"## Test Class: {analysis_result.get('test_class_name', 'Unknown')}\n")
        summary_parts.append(f"## Overall Compliance Score: {analysis_result.get('overall_compliance_score', 'N/A')}\n\n")
        
        # Practices summary
        summary_parts.append("## Best Practices Compliance\n\n")
        practices_report = analysis_result.get('practices_report', [])
        
        for practice in practices_report:
            code = practice.get('practice_code', '')
            title = practice.get('practice_title', '')
            score = practice.get('compliance_score', 'N/A')
            compliant = practice.get('compliant_methods', 0)
            non_compliant = practice.get('non_compliant_methods', 0)
            
            status_emoji = "✅" if score == "100%" else "⚠️" if score != "N/A" else "⚪"
            
            summary_parts.append(
                f"{status_emoji} **{code}: {title}**\n"
                f"   - Score: {score}\n"
                f"   - Compliant: {compliant}, Non-compliant: {non_compliant}\n\n"
            )
        
        # Method-level improvements
        summary_parts.append("## Method-Level Improvements\n\n")
        test_methods = analysis_result.get('test_methods', [])
        
        for method in test_methods:
            method_name = method.get('test_method_name', 'Unknown')
            method_score = method.get('method_compliance_score', 'N/A')
            
            summary_parts.append(f"### {method_name}\n")
            summary_parts.append(f"Compliance Score: {method_score}\n\n")
            
            # List non-compliant practices
            practices_eval = method.get('practices_evaluation', [])
            non_compliant_practices = [
                p for p in practices_eval if p.get('status') == '❌'
            ]
            
            if non_compliant_practices:
                summary_parts.append("**Issues Found:**\n")
                for practice in non_compliant_practices:
                    summary_parts.append(
                        f"- {practice.get('practice_code')}: {practice.get('justification')}\n"
                    )
                summary_parts.append("\n")
        
        return ''.join(summary_parts)
    
    def __repr__(self) -> str:
        return "TestImproverAgent()"
